stages:
    - build
build_image:
  stage: build
  script:
    - docker build --no-cache=true -t node77790-priv-reg.demo.jelastic.com:11007/glassfish:$CI_BUILD_REF_NAME .
    - docker push node77790-priv-reg.demo.jelastic.com:11007/glassfish:$CI_BUILD_REF_NAME
